const DEFAULT_DOORS = [
  {
    "id": "door-1",
    "dk": "DK/1",
    "designation": "VDa.291",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M — Master",
    "lock": "spv 6000",
    "latch": "без защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-2",
    "dk": "DK/2",
    "designation": "VDa.290",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M — Master",
    "lock": "spv 6000",
    "latch": "без защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-3",
    "dk": "DK/3",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-4",
    "dk": "DK/4",
    "designation": "VDa.284",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-5",
    "dk": "DK/5",
    "designation": "VD.185",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "с верхней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-6",
    "dk": "DK/6",
    "designation": "VD.168",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "эвакуация не обозначена (по ходу)"
  },
  {
    "id": "door-7",
    "dk": "DK/7",
    "designation": "VD.166",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 2000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника по ходу"
  },
  {
    "id": "door-8",
    "dk": "DK/8",
    "designation": "LA.12.1",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "раздвижные",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-9",
    "dk": "DK/9",
    "designation": "VD.179",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "с верхней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-10",
    "dk": "DK/10",
    "designation": "VD.167",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-11",
    "dk": "DK/12",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-12",
    "dk": "DK/13",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-13",
    "dk": "DK/14",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-14",
    "dk": "DK/15",
    "designation": "VD.149",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника не верна (по ходу)"
  },
  {
    "id": "door-15",
    "dk": "DK/18",
    "designation": "LD.106",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-16",
    "dk": "DK/20",
    "designation": "VD.55",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника неверна (паника по ходу)"
  },
  {
    "id": "door-17",
    "dk": "DK/21",
    "designation": "VD.56",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника неверна (паника по ходу)"
  },
  {
    "id": "door-18",
    "dk": "DK/22",
    "designation": "VD.293",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-19",
    "dk": "DK/23",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-20",
    "dk": "DK/24",
    "designation": "",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-21",
    "dk": "DK/25",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-22",
    "dk": "DK/26",
    "designation": "",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-23",
    "dk": "DK/27",
    "designation": "",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-24",
    "dk": "DK/28",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-25",
    "dk": "DK/29",
    "designation": "",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-26",
    "dk": "DK/30",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-27",
    "dk": "DK/33",
    "designation": "",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-28",
    "dk": "DK/35",
    "designation": "VD.293",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-29",
    "dk": "DK/38",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-30",
    "dk": "DK/40",
    "designation": "VD.205",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-31",
    "dk": "DK/41",
    "designation": "VD.188",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-32",
    "dk": "DK/42",
    "designation": "VDa.437",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-33",
    "dk": "DK/43",
    "designation": "VDa.434",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-34",
    "dk": "DK/44",
    "designation": "VD.203",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-35",
    "dk": "DK/45",
    "designation": "VD.210",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "AS — fail secure",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-36",
    "dk": "DK/46",
    "designation": "VD.204",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-37",
    "dk": "DK/47",
    "designation": "VD.187",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-38",
    "dk": "DK/48",
    "designation": "VD.201",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-39",
    "dk": "DK/50",
    "designation": "VD.192",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "эвакуации нет (паника по ходу)"
  },
  {
    "id": "door-40",
    "dk": "DK/51",
    "designation": "VD.195",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-41",
    "dk": "DK/52",
    "designation": "VD.190",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-42",
    "dk": "DK/53",
    "designation": "VD.194",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M — Master",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": "уже работает (сервер)"
  },
  {
    "id": "door-43",
    "dk": "DK/54",
    "designation": "VD.196",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svz 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника не верна (по ходу)"
  },
  {
    "id": "door-44",
    "dk": "DK/55",
    "designation": "VD.199",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-45",
    "dk": "DK/56",
    "designation": "VD.200",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-46",
    "dk": "DK/57",
    "designation": "VD.189",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-47",
    "dk": "DK/58",
    "designation": "VD.237",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "нет замков и защёлок",
    "latch": "",
    "mode": "",
    "panic": "не та дверь"
  },
  {
    "id": "door-48",
    "dk": "DK/59",
    "designation": "LG.28",
    "zone": "Офисное здание",
    "floor": "2 эт",
    "access": "M — Master",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-49",
    "dk": "DK/61",
    "designation": "LD.121",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M — Master",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-50",
    "dk": "DK/62",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-51",
    "dk": "DK/63",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-52",
    "dk": "DK/64",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-53",
    "dk": "DK/65",
    "designation": "VD.224",
    "zone": "Цех",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-54",
    "dk": "DK/66",
    "designation": "",
    "zone": "",
    "floor": "",
    "access": "",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-55",
    "dk": "DK/67",
    "designation": "1.202",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-56",
    "dk": "DK/69",
    "designation": "VD.197",
    "zone": "Цех",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-57",
    "dk": "DK/70",
    "designation": "VD.226",
    "zone": "Цех",
    "floor": "2 эт",
    "access": "M-S — Master Slave",
    "lock": "svp 6000",
    "latch": "с нижней защёлкой",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  },
  {
    "id": "door-58",
    "dk": "DK/71",
    "designation": "",
    "zone": "Цех",
    "floor": "1 эт",
    "access": "M-S — Master Slave",
    "lock": "",
    "latch": "",
    "mode": "",
    "panic": ""
  },
  {
    "id": "door-59",
    "dk": "DK/72",
    "designation": "VD.165",
    "zone": "Офисное здание",
    "floor": "1 эт",
    "access": "M — Master",
    "lock": "svp 6000",
    "latch": "без нижней защёлки",
    "mode": "RS — fail safe",
    "panic": "паника верна"
  }
];
